### ISSUE TITLE
Support optional config sources

### ISSUE THREAD

**Issue by Francessco121** [Francessco121/dart-embedded-config#3]
It would be super useful to allow build.yaml configs to specify whether a config source is optional. For example, an app could have a `config.local.json` file that doesn't exist by default (and is ignored by source control), but developers can create to optionally override config for development. This could allow different developers to use different dev configs without worrying about committing them to a repository.

Could look something like this:
```yaml
# Multi-source example
targets:
  $default:
    builders:
      embedded_config:
        options:
          app_config:
            source:
              - lib/app_config.json
              - path: lib/app_config.local.json
                optional: true

# Single-source example
targets:
  $default:
    builders:
      embedded_config:
        options:
          app_config:
            # Note: not strictly required, a list with a single item would work 
            # for both multi and single without additional work
            source:
              path: lib/app_config.local.json
              optional: true
            inline:
              key: value
```
